import type { SupportedLanguage, ExperienceLevel } from './types';
import {
  getCountryOptionsLazy,
  getStateOptionsLazy,
  getCityOptionsLazy,
  getCountryNameLazy,
  getStateNameLazy
} from './geographical-data';

// Extract professions from translation keys
export const PROFESSION_KEYS = [
  'chief-executive',
  'administration-and-planning-manager',
  'policy-and-planning-manager',
  'business-services-and-administration-manager',
  'sales-marketing-and-development-manager',
  'production-and-specialized-services-manager',
  'hospitality-retail-and-other-services-manager',
  'science-and-engineering-professional',
  'software-developer',
  'systems-analyst',
  'database-designer',
  'network-professional',
  'health-professional',
  'doctor',
  'nurse',
  'pharmacist',
  'veterinarian',
  'teaching-professional',
  'professor',
  'secondary-education-teacher',
  'primary-school-teacher',
  'business-and-administration-professional',
  'accountant',
  'financial-analyst',
  'human-resources-professional',
  'information-and-communications-technology-professional',
  'legal-professional',
  'lawyer',
  'judge',
  'culture-arts-and-design-professional',
  'author',
  'journalist',
  'artist',
  'designer',
  'science-and-engineering-associate-professional',
  'engineering-technician',
  'drafter',
  'health-associate-professional',
  'medical-technician',
  'nursing-associate-professional',
  'business-and-administration-associate-professional',
  'insurance-representative',
  'estate-agent',
  'legal-social-and-cultural-associate-professional',
  'legal-associate-professional',
  'social-worker',
  'information-and-communications-technician',
  'computer-technician',
  'telecommunications-technician',
  'general-and-keyboard-clerk',
  'secretary',
  'data-entry-clerk',
  'customer-services-clerk',
  'customer-service-representative',
  'receptionist',
  'numerical-and-material-recording-clerk',
  'accounting-associate-professional',
  'bookkeeper',
  'other-clerical-support-worker',
  'mail-carrier',
  'filing-clerk',
  'personal-service-worker',
  'travel-attendant',
  'cook',
  'waiter',
  'hairdresser',
  'housekeeper',
  'protective-services-worker',
  'security-guard',
  'police-officer',
  'firefighter',
  'sales-worker',
  'shop-salesperson',
  'cashier',
  'sales-representative',
  'market-oriented-skilled-agricultural-worker',
  'farmer',
  'livestock-producer',
  'crop-grower',
  'market-oriented-skilled-forestry-fishery-and-hunting-worker',
  'logger',
  'fisherman',
  'subsistence-farmer-fisherman-hunter-and-gatherer',
  'building-and-related-trades-worker',
  'carpenter',
  'electrician',
  'plumber',
  'painter',
  'metal-machinery-and-related-trades-worker',
  'welder',
  'machinist',
  'mechanic',
  'handicraft-and-printing-worker',
  'potter',
  'tailor',
  'printer',
  'electrical-and-electronic-trades-worker',
  'food-processing-woodworking-garment-and-other-craft-and-related-trades-worker',
  'stationary-plant-and-machine-operator',
  'power-plant-operator',
  'machine-operator',
  'assembler',
  'product-assembler',
  'electronics-assembler',
  'driver-and-mobile-plant-operator',
  'truck-driver',
  'bus-driver',
  'taxi-driver',
  'cleaner-and-helper',
  'domestic-helper',
  'building-cleaner',
  'kitchen-helper',
  'agricultural-forestry-and-fishery-laborer',
  'farm-worker',
  'gardener',
  'laborer-in-mining-construction-manufacturing-and-transport',
  'construction-laborer',
  'factory-worker',
  'food-preparation-assistant',
  'street-and-related-service-worker',
  'content-creator',
  'social-media-manager',
  'digital-marketing-specialist',
  'uxui-designer',
  'data-scientist',
  'machine-learning-engineer',
  'devops-engineer',
  'product-manager',
  'consultant',
  'entrepreneur',
  'freelancer',
  'student',
  'retired',
  'unemployed',
  'other'
] as const;

// All available skills from translation files
export const POPULAR_SKILL_KEYS = [
  // Programming & Technology
  'javascript',
  'typescript',
  'python',
  'java',
  'c#',
  'c++',
  'go',
  'rust',
  'php',
  'ruby',
  'swift',
  'kotlin',
  'react',
  'vuejs',
  'angular',
  'svelte',
  'nextjs',
  'nodejs',
  'expressjs',
  'django',
  'flask',
  'postgresql',
  'mysql',
  'mongodb',
  'redis',
  'aws',
  'azure',
  'google-cloud',
  'docker',
  'kubernetes',
  'machine-learning',
  'artificial-intelligence',
  'data-science',
  'data-analysis',
  'statistics',
  'cybersecurity',
  'network-administration',
  'database-administration',
  'system-administration',
  'web-development',
  'mobile-development',
  'game-development',
  'software-testing',
  'devops',

  // Design & Creative
  'graphic-design',
  'uiux-design',
  'web-design',
  'brand-design',
  'logo-design',
  'typography',
  'adobe-photoshop',
  'adobe-illustrator',
  'figma',
  'sketch',
  'canva',
  'video-editing',
  'animation',
  'photography',
  'digital-photography',
  'portrait-photography',
  'landscape-photography',
  'photo-editing',
  'drawing',
  'painting',
  'digital-art',
  'illustration',
  'sculpture',
  'ceramics',
  'jewelry-making',
  '3d-modeling',
  'cad-design',
  'industrial-design',
  'interior-design',
  'fashion-design',

  // Business & Management
  'project-management',
  'product-management',
  'business-analysis',
  'strategic-planning',
  'leadership',
  'team-management',
  'human-resources',
  'recruitment',
  'sales',
  'marketing',
  'digital-marketing',
  'social-media-marketing',
  'content-marketing',
  'email-marketing',
  'seo',
  'sem',
  'ppc-advertising',
  'financial-analysis',
  'accounting',
  'bookkeeping',
  'budgeting',
  'investment-analysis',
  'risk-management',
  'supply-chain-management',
  'operations-management',
  'quality-assurance',
  'process-improvement',
  'business-development',
  'negotiation',
  'contract-management',
  'vendor-management',

  // Communication & Writing
  'public-speaking',
  'presentation-skills',
  'technical-writing',
  'creative-writing',
  'copywriting',
  'content-creation',
  'journalism',
  'blogging',
  'editing',
  'proofreading',
  'translation',
  'interpretation',
  'customer-service',
  'client-relations',
  'conflict-resolution',
  'mediation',
  'storytelling',
  'interviewing',
  'active-listening',
  'cross-cultural-communication',

  // Education & Training
  'teaching',
  'training-development',
  'curriculum-design',
  'educational-technology',
  'e-learning',
  'mentoring',
  'coaching',
  'workshop-facilitation',
  'adult-education',
  'child-development',
  'special-education',
  'educational-assessment',
  'research-methods',
  'academic-writing',

  // Health & Wellness
  'first-aid',
  'cpr',
  'medical-knowledge',
  'nursing',
  'physical-therapy',
  'mental-health-support',
  'nutrition',
  'fitness-training',
  'yoga',
  'meditation',
  'mindfulness',
  'stress-management',
  'health-coaching',
  'massage-therapy',
  'acupuncture',
  'herbal-medicine',
  'alternative-medicine',

  // Trades & Manual Skills
  'carpentry',
  'plumbing',
  'electrical-work',
  'hvac',
  'welding',
  'automotive-repair',
  'motorcycle-repair',
  'appliance-repair',
  'computer-repair',
  'electronics-repair',
  'decorating',
  'tiling',
  'roofing',
  'masonry',
  'landscaping',
  'construction',
  'home-improvement',
  'furniture-making',

  // Culinary
  'cooking',
  'baking',
  'pastry-making',
  'food-preparation',
  'menu-planning',
  'recipe-development',
  'food-safety',
  'kitchen-management',
  'wine-knowledge',
  'bartending',
  'coffee-making',
  'brewing',
  'food-photography',
  'catering',
  'meal-planning',
  'nutrition-planning',
  'dietary-planning',

  // Music & Performance
  'music-production',
  'audio-engineering',
  'music-composition',
  'singing',
  'guitar',
  'piano',
  'drums',
  'violin',
  'bass',
  'saxophone',
  'music-theory',
  'sound-design',
  'podcast-production',
  'acting',
  'theater',
  'film-making',
  'screenwriting',
  'video-production',
  'broadcasting',
  'stand-up-comedy',
  'improvisation',
  'dance',
  'ballet',
  'hip-hop',
  'salsa',
  'ballroom-dancing',

  // Sports & Fitness
  'football',
  'basketball',
  'soccer',
  'tennis',
  'golf',
  'swimming',
  'running',
  'cycling',
  'hiking',
  'rock-climbing',
  'skiing',
  'snowboarding',
  'surfing',
  'martial-arts',
  'boxing',
  'wrestling',
  'gymnastics',
  'track-and-field',
  'baseball',
  'volleyball',
  'badminton',
  'table-tennis',
  'sports-coaching',
  'personal-training',
  'athletic-training',

  // Outdoor & Survival
  'camping',
  'backpacking',
  'fishing',
  'hunting',
  'map-reading',
  'orienteering',
  'wilderness-survival',
  'fire-making',
  'foraging',
  'knot-tying',
  'rope-work',
  'sailing',
  'kayaking',
  'canoeing',
  'mountain-climbing',
  'cave-exploration',
  'wildlife-tracking',

  // Gardening & Environment
  'gardening',
  'organic-gardening',
  'hydroponics',
  'permaculture',
  'composting',
  'plant-propagation',
  'tree-care',
  'flower-arranging',
  'botanical-knowledge',
  'pest-management',
  'soil-management',
  'irrigation',
  'greenhouse-management',
  'urban-farming',
  'beekeeping',

    // Crafts & Hobbies
  'knitting',
  'crocheting',
  'sewing',
  'quilting',
  'embroidery',
  'cross-stitch',
  'woodworking',
  'metalworking',
  'glassblowing',
  'pottery',
  'candle-making',
  'soap-making',
  'leatherworking',
  'bookbinding',
  'origami',
  'calligraphy',
  'scrapbooking',
  'model-building',

  // Research & Analysis
  'data-collection',
  'statistical-analysis',
  'literature-review',
  'critical-thinking',
  'problem-solving',
  'mathematical-modeling',
  'scientific-method',
  'laboratory-skills',
  'microscopy',
  'spectroscopy',
  'chemical-analysis',
  'fieldwork',
  'survey-design',
  'grant-writing',

  // Personal Development
  'time-management',
  'organization',
  'goal-setting',
  'self-discipline',
  'emotional-intelligence',
  'decision-making',
  'creative-thinking',
  'innovation',
  'adaptability',
  'resilience',
  'self-motivation',
  'continuous-learning',
  'self-reflection',
  'networking',
  'relationship-building',
  'empathy',
  'cultural-sensitivity',
  'team-collaboration',
  
  // Community & Social
  'volunteer-coordination',
  'community-organizing',
  'event-planning',
  'party-planning',
  'hospitality',
  'customer-relations',
  'diplomacy',
  'persuasion',
  'influence',
  'social-media-engagement',

  // Digital Literacy
  'computer-literacy',
  'internet-research',
  'email-management',
  'social-media-management',
  'online-marketing',
  'e-commerce',
  'digital-privacy',
  'cybersecurity-awareness',
  'podcast-creation',
  'youtube-creation',
  'live-streaming',
  'online-teaching',
  'virtual-collaboration',

    // Transportation & Logistics
  'driving',
  'truck-driving',
  'motorcycle-riding',
  'bicycle-maintenance',
  'navigation',
  'route-planning',
  'logistics-coordination',
  'warehouse-management',
  'inventory-management',
  'shipping-and-receiving',

  // Finance & Investment
  'personal-finance',
  'investment-planning',
  'tax-preparation',
  'insurance-knowledge',
  'real-estate',
  'cryptocurrency',
  'trading',
  'financial-planning',
  'retirement-planning',
  'debt-management',

  // Languages
  'spanish',
  'french',
  'german',
  'italian',
  'portuguese',
  'russian',
  'chinese',
  'japanese',
  'korean',
  'arabic',
  'hindi',
  'dutch',
  'swedish',
  'norwegian',
  'danish',
  'finnish',
  'polish',
  'turkish',

  // Entertainment & Games
  'magic-tricks',
  'juggling',
  'balloon-animals',
  'face-painting',
  'card-games',
  'board-games',
  'chess',
  'bridge',
  'poker',
  'trivia-knowledge',
  'speed-reading',
  'memory-techniques',
  'escape-rooms',
  'puzzle-solving',
  'crossword-puzzles',
  'sudoku',
  'word-games'
] as const;

// Use lazy-loading geographical data with custom overrides
export function getCountryOptions() {
  return getCountryOptionsLazy();
}

// Get states/provinces for a specific country
export function getStateOptions(countryCode: string) {
  return getStateOptionsLazy(countryCode);
}

// Get cities for a specific country (and optionally state)
export function getCityOptions(countryCode: string, stateCode?: string) {
  return getCityOptionsLazy(countryCode, stateCode);
}

// Helper function to get country name by ISO code
export function getCountryName(isoCode: string): string {
  return getCountryNameLazy(isoCode);
}

// Helper function to get state name by ISO code
export function getStateName(countryCode: string, stateCode: string): string {
  return getStateNameLazy(countryCode, stateCode);
}

export const LANGUAGES: Record<SupportedLanguage, string> = {
  en: 'English',
  de: 'Deutsch',
  fr: 'Français',
  es: 'Español',
  it: 'Italiano',
  pt: 'Português',
  nl: 'Nederlands',
  pl: 'Polski',
  ru: 'Русский',
  ja: '日本語',
  ko: '한국어',
  zh: '中文',
  ar: 'العربية',
  hi: 'हिन्दी'
};

export const EXPERIENCE_LEVELS: Record<ExperienceLevel, string> = {
  intern: 'Intern',
  entry: 'Entry Level (0-2 years)',
  mid: 'Mid Level (3-5 years)',
  senior: 'Senior Level (6-10 years)',
  lead: 'Lead/Principal (10+ years)',
  executive: 'Executive/C-Level'
};

// Helper function to get profession options for a select component
export function getProfessionOptions(t: (key: string) => string) {
  return PROFESSION_KEYS.map(key => ({
    value: key,
    label: t(`professions.${key}`)
  })).sort((a, b) => a.label.localeCompare(b.label));
}

// Helper function to get skill suggestions
export function getSkillSuggestions(t: (key: string) => string) {
  return POPULAR_SKILL_KEYS.map(key => ({
    value: key,
    label: t(`skills.${key}`)
  }));
}

// Helper function to get experience level options with explicit namespace handling
export function getExperienceLevelOptions(t: (key: string) => string) {
  return (Object.keys(EXPERIENCE_LEVELS) as ExperienceLevel[]).map(key => ({
    value: key,
    // Ensure we use the correct translation key without double prefixes
    label: t(`options.experienceLevel.${key}`)
  }));
} 